### ISSUE TITLE
Deprecate @octokit/oauth-login-url package on npm

### ISSUE THREAD

**Issue by frangio** [octokit/oauth-authorization-url.js#43]
Please mark the `@octokit/oauth-login-url` package as deprecated on NPM. I was using it and only found out that it was deprecated by coming to this repository.

**Comment by gr2m** [comment]
This package is not deprecated. Where did you see a deprecation notice about this package?

**Comment by frangio** [comment]
Sorry for the confusion. I only meant the old package name <code>@octokit/oauth-<b>login</b>-url</code>. A deprecation notice on that package would let people know that there is a new package name. On the other hand, the upgrade/migration may not be necessary for some and the deprecation notice would be a nuisance for them... Feel free to ignore this suggestion of course.

**Comment by gr2m** [comment]
Ah good catch! Sorry I totally missed that.

**Comment by gr2m** [comment]
Done

```
➜  npm info @octokit/oauth-login-url deprecated
@octokit/oauth-login-url has been renamed to @octokit/oauth-authorization-url
```
